# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  postgres:
    env_file: .env
    image: postgres:14

  backup:
    env_file: .env
    build:
      context: .